version: "3.9"

services:
  database:
    image: postgres
    container_name: backend-sistema
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gerenciaclientes
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
